// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnaaxnpffaoqjyccpeso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuYWF4bnBmZmFvcWp5Y2NwZXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTIwMTEsImV4cCI6MjA2MTkyODAxMX0.3yEA-jW039yv8kONvClhA9D0YODALfj0qrmN6lfGaFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);